### ISSUE TITLE
little blurb that appears when you google it

### ISSUE THREAD

**Issue by offtheshelffarm** [offtheshelffarm/offtheshelffarm#10]
just trying to do what you taught me!

Can we edit the subheader of what shows up when you google off the shelf farm?
Currently it reads "Raising grass-fed eggs, lamb, and chicken in The Berkshires."

Would like it to read: "Off the Shelf Farm is a small farm raising grass-fed eggs, lamb, and chicken in The Berkshires."

you da best.
also, you still planning to work FM this weekend w/ us?

**Comment by russellsamora** [comment]
Yup. Can we add this to make it ... 

"Off the Shelf Farm is a small farm raising grass-fed eggs, lamb, and chicken in The Berkshires. Off the Shelf eggs are available at Guido’s Fresh Marketplace and The Berkshire Food Co-op in Great Barrington." 

? This will improve search results especially when people are searching for "Off the shelf eggs"

Yes. I'll be workin!

**Comment by offtheshelffarm** [comment]
Yes!
